spring.application.name=ComplaintService


# Database Connection
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/citywatch_post?createDatabaseIfNotExist=true}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:root}


spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.cloud.gateway.globalcors.add-to-simple-url-handler-mapping=true

# Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


##cloudinary config

cloudinary.cloudName=${CLOUDINARY_CLOUD_NAME}
cloudinary.apiKey=${CLOUDINARY_API_KEY}
cloudinary.apiSecret=${CLOUDINARY_API_SECRET}

jwt.secret=${JWT_SECRET}
jwt.expiration=3600000

spring.servlet.multipart.max-file-size = 10MB
spring.servlet.multipart.max-request-size =10MB

server.port = 8082

eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8761/eureka/}
eureka.instance.prefer-ip-address=true



spring.data.redis.host=${REDIS_HOST:redis}
spring.data.redis.port=${REDIS_PORT:6379}

spring.data.redis.timeout=60000


razorpay.key_id=${RAZORPAY_KEY_ID}
razorpay.key_secret=${RAZORPAY_KEY_SECRET}


eureka.instance.hostname=localhost
eureka.instance.ip-address=127.0.0.1

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always