package com.userservice.entity;

public enum WorkType {
    ELECTRICIAN,
    PLUMBER,
    CARPENTER,
    CLEANER,
    ROAD_REPAIR,
    GARBAGE_COLLECTION,
    STREET_LIGHT_MAINTENANCE,
    WATER_SUPPLY,
    DRAINAGE,
    SEWERAGE,
    TREE_MAINTENANCE,
    CIVIL_WORK,
    PEST_CONTROL,
    PARK_MAINTENANCE

}