

# Server Port
server.port=8080

# App Name
spring.application.name=api-gateway

# ===============================
# ROUTE 1 ? USER SERVICE
# ===============================

# Gateway route to UserSer
spring.cloud.gateway.routes[0].id=UserSer
spring.cloud.gateway.routes[0].uri=lb://UserSer
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/**,/admin/**,/worker/**
spring.cloud.gateway.routes[0].filters[0]=RewritePath=/api/(?<segment>.*), /${segment}

eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8761/eureka/}
spring.cloud.gateway.discovery.locator.enabled=true

spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedOrigins=http://localhost:4200
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedMethods=GET,POST,PUT,DELETE,OPTIONS
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedHeaders=*
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowCredentials=true
spring.cloud.gateway.globalcors.add-to-simple-url-handler-mapping=true

spring.cloud.gateway.routes[1].id=ComplaintService
spring.cloud.gateway.routes[1].uri=lb://ComplaintService
spring.cloud.gateway.routes[1].predicates[0]=Path=/posts/**,/likes/**,/comments/**,/notifications/**

#eureka.instance.hostname=localhost
#eureka.instance.ip-address=127.0.0.1
eureka.instance.prefer-ip-address=true



management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always